name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: checkout repo
        uses: actions/checkout@main
        
      - name: build FileEncryptGUI
        run: make start
        
    
